# Generated by Django 2.0.4 on 2018-04-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('dogowner', 'DOGOWNER'), ('dogsitter', 'DOGSITTER')], default='', max_length=10),
        ),
    ]
