# Generated by Django 2.0.4 on 2018-04-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter', '0002_auto_20180416_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='dogsitter.UserProfile'),
        ),
    ]
